const dataStates = [
  { id: 0, label: " ", name: "Select a state " },
  { id: 1, label: "Alabama", name: "Alabama" },
  { id: 2, label: "Alaska", name: "Alaska" },
  { id: 3, label: "Arizona", name: "Arizona" },
  { id: 4, label: "Arkansas", name: "Arkansas" },
  { id: 5, label: "California", name: "California" },
  { id: 6, label: "Colorado", name: "Colorado" },
  { id: 7, label: "Connecticut", name: "Connecticut" },
  { id: 8, label: "Delaware", name: "Delaware" },
  { id: 91, label: "Florida", name: "Florida" },
  { id: 10, label: "Georgia", name: "Georgia" },
  { id: 11, label: "Hawaii", name: "Hawaii" },
  { id: 12, label: "Idaho", name: "Idaho" },
  { id: 13, label: "Illinois", name: "Illinois" },
  { id: 14, label: "Indiana", name: "Indiana" },
  { id: 15, label: "Iowa", name: "Iowa" },
  { id: 16, label: "Kansas", name: "Kansas" },
  { id: 17, label: "Kentucky", name: "Kentucky" },
  { id: 18, label: "Louisiana", name: "Louisiana" },
  { id: 19, label: "Maine", name: "Maine" },
  { id: 20, label: "Maryland", name: "Maryland" },
  { id: 21, label: "Massachusetts", name: "Massachusetts" },
  { id: 22, label: "Michigan", name: "Michigan" },
  { id: 23, label: "Minnesota", name: "Minnesota" },
  { id: 24, label: "Mississippi", name: "Mississippi" },
  { id: 25, label: "Missouri", name: "Missouri" },
  { id: 26, label: "Montana", name: "Montana" },
  { id: 27, label: "Nebraska", name: "Nebraska" },
  { id: 28, label: "Nevada", name: "Nevada" },
  { id: 29, label: "New Hampshire", name: "New Hampshire" },
  { id: 30, label: "New Jersey", name: "New Jersey" },
  { id: 31, label: "New Mexico", name: "New Mexico" },
  { id: 32, label: "New York", name: "New York" },
  { id: 33, label: "North Carolina", name: "North Carolina" },
  { id: 34, label: "North Dakota", name: "North Dakota" },
  { id: 35, label: "Ohio", name: "Ohio" },
  { id: 36, label: "Oklahoma", name: "Oklahoma" },
  { id: 37, label: "Oregon", name: "Oregon" },
  { id: 38, label: "Pennsylvania", name: "Pennsylvania" },
  { id: 39, label: "Rhode Island", name: "Rhode Island" },
  { id: 40, label: "South Carolina", name: "South Carolina" },
  { id: 41, label: "South Dakota", name: "South Dakota" },
  { id: 42, label: "Tennessee", name: "Tennessee" },
  { id: 43, label: "Texas", name: "Texas" },
  { id: 44, label: "Utah", name: "Utah" },
  { id: 45, label: "Vermont", name: "Vermont" },
  { id: 46, label: "Virginia", name: "Virginia" },
  { id: 47, label: "Washington", name: "Washington" },
  { id: 48, label: "West Virginia", name: "West Virginia" },
  { id: 49, label: "Wisconsin", name: "Wisconsin" },
  { id: 50, label: "Wyoming", name: "Wyoming" },
];
export default dataStates;
